;;;; bare bones scheme compiler


(define fixnum-range '(-4611686018427387904 . 4611686018427387903))
(define temporary-registers '(rax r11 r15))
(define argument-registers '(SELF rcx rdx rsi rdi r8 r9 r10 r12))
(define basic-implementation-features '(bones srfi-0 srfi-6 srfi-8 srfi-7))
(define word-size 8)


(define (compile code . options)
  (set! lambda-id-counter 0)
  (set! implementation-features
    (append (map string->symbol (collect-options 'feature: options))
	    basic-implementation-features))
  (set! file-search-path
    (append (collect-options 'library-path: options) '(".")))
  (expand-syntax (generate-cond-expand implementation-features))
  (let* ((code (expand-syntax
		(match code
		  (('begin ('program . _))
		   (expand-program (cadr code)))
		  (_ code))))
	 (_ (when (option 'expand: options) 
	      (pp code)
	      (exit)))
	 (dumpcc (option 'dump-cc: options))
	 (dumpcps (option 'dump-cps: options))
	 (dumpserial (not (option 'dump-nested: options)))
	 (dumpcompiled (option 'dump: options))
	 (outfile (option 'output-file: options))
	 (code (canonicalize-expression code))
	 (defs code (cps code))
	 (_ (when dumpcps
	      (dump-expressions code dumpserial)
	      (exit)))
	 (code (detect-unused-variables code))
	 (_ (when dumpcompiled
	      (dump-expressions code dumpserial)
	      (exit)))
	 (ccode (cc code '())))
    (when dumpcc
      (dump-expressions ccode dumpserial)
      (exit))
    ;;XXX add pass that assigns closure-id's to target variables, for adding comments in
    ;;    generated output.
    ((if outfile
	 (lambda (thunk)
	   (with-output-to-file outfile thunk))
	 (lambda (thunk) (thunk)))
     (cut generate-code defs ccode))))

(define (compile-file fname . options)
  (apply compile (read-forms fname) options))

(define (generate-code defs code)
  (set! label-counter 0)
  (generate-header)
  (set! literals-to-be-translated '())
  (set! primitives '())
  (generate-closures code)
  (generate-globals defs)
  (generate-literals)
  (generate-primitives)
  (generate-trailer))

(define (generate-header)
  (emit ";;; GENERATED BY BONES\n")
  (emit "%include \"boneslib.s\"\n"))

(define (generate-trailer)
  (emit ";;; END OF GENERATED CODE\n"))

(define (generate-globals defs)
  (emit " section .data\nglobals:\n")
  (for-each 
   (lambda (def)
     (emit (mangle-identifier def) ": dq undefined\n"))
   defs)
  (emit "endglobals:\n"))

(define primitives '())

(define (generate-primitives)
  (emit " section .data\n")
  (for-each
   (match-lambda
     ((l . name)
      (emit l ": dq CLOSURE | 1\n dq " name "\n")))
   primitives))

(define closures-to-be-translated '())

(define (generate-closures top)
  (set! closures-to-be-translated (list top))
  (emit " section .text\ntoplevel:\n")
  (do ()
      ((null? closures-to-be-translated))
    (translate-closure (pop! closures-to-be-translated))))

(define primitives '())

(define literals-to-be-translated '())
(define string-literals '())
(define symbol-table '())

(define (generate-literals)
  (set! string-literals '())
  (set! symbol-table '())
  (emit " section .data\n")
  (do ()
      ((null? literals-to-be-translated))
    (match-let (((l . c) (pop! literals-to-be-translated)))
      (translate-literal l c)))
  (generate-strings)
  (generate-symbol-table))

(define (generate-strings)
  (emit " section .data\n")
  (for-each
   (match-lambda
     ((l . str)
      (emit "align 8\n" l ": dq STRING | " (string-length str) "\n")
      (when (positive? (string-length str))
	(emit " db " (join (map (o number->string char->integer) (string->list str)) ",") "\n"))))
   string-literals))

(define (generate-symbol-table)
  (emit " section .data\nsymbol_literals:\n")
  (for-each (lambda (l) (emit " dq " (cdr l) "\n")) symbol-table)
  (emit " dq false\n"))

(define (fixnum? n)
  (and (number? n) (exact? n) (<= (car fixnum-range) n (cdr fixnum-range))))

(define (register-literal c)
  (let ((l1 (label)))
    (push! (cons l1 c) literals-to-be-translated)
    l1))

(define (translate-literal l c)
  (cond ((fixnum? c) (emit l " equ FIX(" c ")\n"))
	((number? c)
	 (emit "align 8\n" l ": dq FLONUM | FLONUM_CELLS\n dq __float64__(" (exact->inexact c) ")\n"))
	((pair? c)
	 (let ((lcar (register-literal (car c)))
	       (lcdr (register-literal (cdr c))))
	   (emit "align 8\n" l ": dq PAIR | 2\n dq " lcar "\n dq " lcdr "\n")))
	((vector? c)
	 (let ((ls (map register-literal (vector->list c))))
	   (emit "align 8\n" l ": dq VECTOR | " (length ls) "\n")
	   (for-each (cut emit " dq " <> "\n") ls)))
	((string? c)
	 (push! (cons l c) string-literals))
	((symbol? c)
	 (cond ((assq c symbol-table) =>
		(match-lambda 
		  ((_ . l2) (emit l " equ " l2 "\n"))))
	       (else
		(let ((l1 (register-literal (symbol->string c))))
		  (push! (cons c l) symbol-table)
		  (emit "align 8\n" l ": dq SYMBOL | 1\n dq " l1 "\n")))))
	((char? c)
	 (emit "align 8\n" l ": dq CHAR | 1\n dq FIX(" (char->integer c) ")\n"))
	((null? c)
	 (emit l " equ null\n"))
	((eq? c #t)
	 (emit l " equ true\n"))
	((eq? c #f)
	 (emit l " equ false\n"))
	(else (error "bad literal" c))))

(define label-counter 0)

(define (label)
  (string-append "L" (number->string (inc! label-counter))))

(define environment '())
(define argument-register-count (sub1 (length argument-registers)))

(define (translate/stack x)
  (let ((ret (translate x 'rax)))
    (emit " push rax\n")
    ret))

(define allocating #f)

(define (translate x t)
  (match x
    (('$closure id cap _ _)
     (push! x closures-to-be-translated)
     (set! allocating #t)
     ;;XXX could be optimized to use temp.-registers, at least for #cap <= 3
     (for-each translate/stack (reverse cap)) ; reverse ok here, args are simple
     (emit " mov " t ", CLOSURE | " (add1 (length cap)) "\n mov [ALLOC], " t "\n"
	   " mov qword [ALLOC + CELLS(1)], f_" id "\n")
     (do ((lst cap (cdr lst))
	  (off 2 (add1 off)))
	 ((null? lst))
       (emit " pop qword [ALLOC + CELLS(" off ")]\n"))
     (emit " mov " t ", ALLOC\n add ALLOC, CELLS(" (+ 2 (length cap)) ")\n")
     #t)
    (('let ((vars vals) ...) body)
     (let* ((oldenv environment)
	    (env (extend-environment environment vars))
	    (single (= 1 (length vars))))
       ;; evaluate vals and push on stack
       (for-each
	(lambda (var val)
	  (cond ((assq var env) => 
		 (lambda (a)
		   (cond (single
			  (let ((dest (cdr a)))
			    (cond ((symbol? dest)
				   (translate val 'rax)
				   (emit " mov " dest ", rax\n"))
				  (else
				   (translate val 'rax)
				   (emit " mov [locals + CELLS(" dest ")], rax\n")))))
			 (else
			  (translate val 'rax)
			  (emit " push rax\n")))))
		((simple-expression? val)) ; unused and simple
		(else (translate val 'rax)))) ; unused but not simple
	vars vals)
       (unless single
	 (for-each
	  (lambda (var val)
	    (cond ((assq var env) =>
		   (lambda (a)
		     (let ((dest (cdr a)))
		       (emit "; " dest " = " var "\n")
		       (if (symbol? dest)
			   (emit " pop " dest "\n")
			   (emit " pop qword [locals + CELLS(" dest ")]\n")))))))
	  (reverse vars) (reverse vals)))
       (fluid-let ((environment env))
	 (translate body t))))
    (('$global-set! var val)
     (translate val t)
     (emit " mov [" (mangle-identifier var) "], " t " ; (set! " var " ...)\n")
     #t)
    (('$global-ref var)
     (emit " mov " t ", [" (mangle-identifier var) "] ; " var "\n")
     #t)
    (('$local-ref var)
     (emit " mov " t ", " (lookup-variable var) " ; " var "\n")
     #t)
    (('$local-set! var val)
     (translate val t)
     (emit " mov " (lookup-variable var) ", " t " ; (set! " var " ...)\n")
     #t)
    (('if x y z)
     (translate x t)
     (let ((l1 (label))
	   (l2 (label)))
       (emit " cmp " t ", FALSE\n je " l1 "\n")
       (when (translate y t) ; ret-flag must be the same for both branches
	 (emit " jmp " l2 "\n"))
       (emit l1 ":\n")
       (let ((ret (translate z t)))
	 (emit l2 ":\n")
	 ret)))
    (('$primitive (or ('quote name) name))
     (let ((l1 (label)))
       (push! (cons l1 name) primitives)
       (emit " mov qword " t ", " l1 " ; " name "\n")
       #t))
    (('$box val)
     (translate val t)
     (emit " mov [ALLOC + CELLS(1)], " t "\n mov " t ", VECTOR | 1\n mov [ALLOC], " t "\n"
	   " mov " t ", ALLOC\n add ALLOC, CELLS(2)\n")
     #t)
    (('$box-ref val)
     (translate val t)
     (emit " mov " t ", [" t " + CELLS(1)]\n")
     #t)
    (('$box-set! box val)
     (match-let ((((_ . r1) (_ . r2)) (translate-inline-arguments (list box val))))
       (emit " mov [" r1 " + CELLS(1)], " r2 "\n")
       (unless (eq? t r2) (emit " mov " t ", " r2 "\n"))
       #t))
    (('$inline (or ('quote opr) opr) args ...)
     (assert (<= (length args) (length temporary-registers)) 
	     "too many arguments to `$inline'" args)
     (translate-inline-arguments args)
     (for-each
      (cut emit " " <> "\n")
      (string-split opr ";"))
     (unless (eq? t 'rax) (emit " mov " t ", rax\n"))
     #t)
    (('$allocate (or ('quote type) type) (or ('quote size) size) args ...)
     (assert (<= (length args) (length temporary-registers))
	     "too many arguments to `$allocate'" args)
     (let ((regs (translate-inline-arguments args))
	   (bytevec (not (zero? (bitwise-and type #x10)))))
       (set! allocating #t)
       (do ((regs regs (cdr regs))
	    (off 1 (add1 off)))
	   ((null? regs))
	 (emit " mov [ALLOC + CELLS(" off ")], " (cdar regs) "\n"))
       (emit " mov " t ", TYPECODE(" type ") | " size "\n")
       (emit " mov [ALLOC], " t "\n mov " t ", ALLOC\n add ALLOC, ")
       (if bytevec
	   (emit "CELLS(1) + ALIGNED(" size ")\n")
	   (emit "CELLS(" (add1 size) ")\n"))
       #t))
    (((or '$undefined '$uninitialized))
     (emit " mov " t ", undefined\n")
     #t)
    (('$closure-ref i)
     (emit " mov " t ", [SELF + CELLS(" (+ i 2) ")]\n")
     #t)
    (('quote c)
     (cond ((fixnum? c)
	    (emit " mov " t ", " (encode-fixnum c) " ; '" c "\n"))
	   ((eq? #t c)
	    (emit " SET_T " t "\n"))
	   ((eq? #f c)
	    (emit " mov " t ", FALSE\n"))
	   ((null? c)
	    (emit " mov " t ", null\n"))
	   (else
	    (let ((l1 (register-literal c)))
	      (emit " mov " t ", " l1 "\n"))))
     #t)
    ((op args ...)
     (translate-call x)
     #f)))

(define (simple-expression? exp)
  (match exp
    ;;XXX $inline? $allocate?
    ((or ('quote _)
	 '($undefined)
	 '($uninitialized)
	 ('$closure-ref _)
	 ('$box-ref (? simple-expression?))
	 ('$global-ref _)
	 ('$local-ref _))
     #t)
    (_ #f)))

(define (translate-inline-arguments args)
  (translate/registers args temporary-registers #f))

(define (translate/registers args regs locals?)
  (let* ((argc (length args))
	 (rargs (map cons args 
		     (append (take argc regs)
			     (iota (- argc (length regs)))))))
    (match rargs
      (((arg . reg))			; just a single argument
       (translate arg 'rax)
       (if (symbol? reg)
	   (unless (eq? reg 'rax) (emit " mov " reg ", rax\n"))
	   (emit " mov qword [locals + CELLS(" reg ")], rax\n")))
      (_ (let ((easy hard (partition
			     (match-lambda
			       ((arg . reg)
				(and (simple-expression? arg)
				     ;;XXX could check whether arg is a var already stored in reg
				     (not (blocked-register? reg))
				     (match arg
				       (('$closure-ref i) #f)
				       (('$local-ref var)
					(not (memq (cdr (assq var environment)) regs)))
				       (_ #t)))))
			     rargs)))
	   (for-each
	    (match-lambda
	      ((arg . _)
	       (translate arg 'rax)
	       (emit " push rax\n")))
	    hard)
	   ;; assign easy destinations first to avoid clobbering SELF
	   (for-each
	    (match-lambda
	      ((arg . reg)
	       (cond ((symbol? reg) (translate arg reg))
		     (else
		      (translate arg 'rax)
		      (emit " mov [locals + CELLS(" reg ")], rax\n")))))
	    easy)
	   (for-each
	    (match-lambda
	      ((_ . reg)
	       (if (symbol? reg)
		   (emit " pop " reg "\n")
		   (emit " pop qword [locals + CELLS(" reg ")]\n"))))
	    (reverse hard)))))
    rargs))

(define (blocked-register? reg)
  (or (eq? reg 'SELF)
      (any (match-lambda ((_ . r) (eq? r reg))) environment)))

(define (encode-fixnum n)
  (bitwise-ior (arithmetic-shift n 1) 1))

(define (translate-call x)
  (let ((n (length x)))
    (translate/registers x argument-registers #t)
    (emit " mov rax, [SELF + CELLS(1)]\n mov r11, " n "\n")
    (cond (allocating
	   (let ((l1 (label)))
	     (emit " cmp ALLOC, LIMIT\n ja reclaim\n jmp rax\n")))
	  (else (emit " jmp rax\n")))))

(define (translate-closure exp)
  (match exp
    ((_ id cap llist body)
     (emit "\nf_" id ":\n")
     (translate-llist llist)
     (set! allocating #f)
     (translate body 'rax))))

(define (translate-llist llist)
  (let* ((vars argc rest (parse-lambda-list llist))
	 (nvars (length vars))
	 (lvars (- nvars (length (cdr argument-registers)))))
    ;;XXX the registers for unused variables are not made available
    (set! environment
      (map cons
	   vars
	   (append 
	    (take nvars (cdr argument-registers))
	    (if (positive? lvars)
		(iota lvars)
		'()))))
    (emit "; " environment "\n")
    (when (and rest (not (eq? '$unused rest)))
      (let ((rdest (cdr (assq rest environment))))
	(emit " mov rax, " (add1 argc) "\n call consrest\n")
	(if (symbol? rdest)
	    (emit " mov " rdest ", rax\n")
	    (emit " mov [locals + CELLS(" rdest ")], rax\n"))))))

(define (extend-environment env vars)
  (let* ((vars (filter (lambda (var) (not (eq? var '$unused))) vars))
	 (avail (max 0 (- argument-register-count (length env))))
	 (rcount (min argument-register-count (length env)))
	 (rvars lvars (split-at avail vars)))
    (append 
     (map cons rvars (take (length rvars) (drop rcount (cdr argument-registers))))
     (map cons lvars (iota (length lvars) (- (length env) (sub1 argument-register-count))))
     env)))

(define (lookup-variable var)
  (cond ((assq var environment) =>
	 (match-lambda 
	   ((_ . r)
	    (if (symbol? r)
		r
		(string-append "[locals + CELLS(" (number->string r) ")]")))))
	(else (error "unknown local variable" var))))

(define (command-line-option? str)
  (let ((len (string-length str)))
    (and (> len 1)
	 (char=? #\- (string-ref str 0)))))

(define (usage)
  (display "usage: bones [-o OUTFILE] [-L LIBRARY_PATH] [-feature FEATURE] [-dump] [-expand]" (current-error-port))
  (display "[-dump-cc] [-dump-nested] [-dump-cps] FILENAME\n" (current-error-port))
  (exit 1))

(define (main args)
  (let ((opts '())
	(fname #f))
    (let loop ((args args))
      (match args
	(() 
	 (if fname
	     (apply compile-file fname opts)
	     (usage)))
	(("-o" out . more)
	 (set! opts (cons* 'output-file: out opts))
	 (loop more))
	(("-L" path . more)
	 (set! opts (append (map (cut list 'library-path: <>) (string-split path ":")) opts))
	 (loop more))
	(("-feature" f . more)
	 (set! opts (cons* 'feature: (string->symbol f) opts))
	 (loop more))
	(((? command-line-option? opt) . more)
	 (set! opts (cons* (string->symbol (string-append (substring opt 1 (string-length opt)) ":")) #t opts))
	 (loop more))
	((filename . more)
	 (set! fname filename)
	 (loop more))))))
