#!/bin/sh
# usage: compile FILENAME [NASMOPTION ...]
set -e
input=$1
filename=`basename $1 .scm`
shift
./bones $input -o $filename.s
nasm -f elf64 -g -F dwarf $filename.s -o $filename.o "$@"
exec bin/musl-gcc $filename.o -o $filename
#exec gcc $filename.o -o $filename
