
* Introduction

  This is BONES, a compiler for R5RS Scheme that generates x86_64
  assembler code. BONES is designed to be simple and easy to
  understand, both to reduce the effort to learn and extend the system
  and to keep the complexity of the compiler at a minimum.

  BONES is a batch-compiler, it takes a Scheme source file and
  produces an assembler file to be subsequently assembled into object
  code. It is also a whole-program compiler, which means it does not
  support producing code that is used as a library or for linking
  together separately compiled Scheme programs. The runtime system is
  by default added to user-code before it is compiled, so there are no
  external libraries, with the exception of a few bits from the C
  library ("libc").

  BONES is mostly R5RS-compliant, but intentionally cuts some corners
  to reduce code-size, increase performance and simplify the compiler
  and runtime system. Type-checks are generally omitted, for example.
  Very little error checking is done and arithmetic overflow of small
  integers ("fixnums") is not detected. Some R7RS procedures are
  available in addition to the primitives required for R5RS.

  Since BONES produces assembly-code, build-times are quite short. The
  produced code is CPU- and OS-specific and currently supports only
  x86_64 on Linux or Windows. Porting the system to other
  architectures and operating systems should be (relatively)
  straightforward, as the platform-specific parts of the compiler are
  small and the runtime-system is just a single file of about two
  thousand lines of assembler code.

  The compiler is self-compiling and uses just a few functions from
  the C-library. Removing this dependency and using system-calls
  directly is basically no problem but will need some hand-written
  replacements (mostly related to number<->string conversion).  Code
  compiled with BONES can be easily embedded into programs written in
  other languages as long as they allow calling C functions.

* Portability

  To run programs compiled with BONES (and to run the compiler
  itself), an x86_64 system is required, with support for SSE2 and
  SSE3 instructions. Currently the system only runs under Linux and
  Windows.

* Requirements

  The [[http://www.nasm.us][NASM]] assembler is required on all supported platforms. To link
  the assembled code you will typically need a C development
  environment. 

  On Linux [[http://gcc.gnu.org][GCC]] is the recommended compiler, but you will only need it
  for linking, and for providing the basic C runtime code (CRT).  A
  subset of the functionality provided by this system can be compiled
  to native code that does not need C runtime support - in this case
  all you need is =ld=, the GNU linker.

  On Windows, Microsoft Visual C is supported, and the "Express"
  version can be obtained from the Microsoft website for free.

* Installation

  BONES is written in Scheme and translates Scheme to x86_64
  assembler, specifically, in the syntax accepted by =NASM=, which will
  have to be installed on your system. To link the assembled code you
  will need a linker and C runtime support files, including the C
  library, so a C compiler should be installed as well.

  To build the system, you need the pre-compiled assembler code for
  the "bones" executable, which you can obtain by downloading
  a distribution tarball at this location:

    http://www.call-with-current-continuation.org/bones/bones.tar.gz

    or 

    http://www.call-with-current-continuation.org/bones/bones.zip

  After downloading, unpack the file using the tar(1) command and 
  assemble and link the appropriate assembler file for the compiler:

  - For Linux:

    #+BEGIN_SRC sh
    tar xfz bones.tar.gz
    cd bones-<date>
    nasm -f elf64 bones-x86_64-linux.s -o bones.o
    gcc bones.o -o bones
    #+END_SRC

  - For Windows:

    Unzip the archive and enter the following commands in a command
    shell window that has access to the command-line MSVC development
    tools:

    #+BEGIN_SRC sh
    cd bones-<date>
    nasm -f win64 bones-x86_64-windows.s -o bones.obj
    link /subsystem:console bones.obj /out:bones.exe
    #+END_SRC

  Now you have a compiler, which you can test by entering 

    #+BEGIN_SRC sh
    ./bones
    #+END_SRC

  which should give you some usage information.

  The =bones= executable can be moved anywhere you desire, but assumes
  that some supporting files are in the directory where it is invoked.
  You can use the =-L= command-line option (described below) to set
  the the directory where the supporting files are located.

* Usage

** Compiling Scheme code

   Compiling code is straightforward. The =bones= program will compile
   a single Scheme source file given on the command-line and write the
   generated assembler code to stdout. You will have to assemble and
   link the generated code by hand, subprocesses to do this are not
   invoked automatically. The compiler accepts a few command-line
   options which are described below.

   Optionally, the file given to "bones" may be a /program
   specification/, an extended variant of the configuration language
   described in [[http://srfi.schemers.org/srfi-7][SRFI-7]]. The compiler treats code that consists of a
   single toplevel expression in the form =(program ...)= as a program
   specification. If the source file does not have this form, it is
   treated as if the code where embedded into the following
   specification:

   #+BEGIN_SRC scheme
   (program
     (include "base.scm")
     (code <...your code...>))
   #+END_SRC

** Assembling and linking Executables

   Once the compiler has produced an assembler file, it has to be
   assembled and linked. Using =NASM=, this is done like this:

   #+BEGIN_SRC sh
   nasm -f <FORMAT> <FILENAME> -o <OBJECTFILENAME>
   #+END_SRC

   =<FORMAT>= specifies the output format suitable for the platform on
   which the object file should be linked. For Linux this is =elf64=,
   for Windows =win64=.

   Linking is done by invoking the appropriate linker for the target
   platform. On Linux this is done by the "gcc" compiler driver, which
   also adds the necessary C runtime libraries needed:

   #+BEGIN_SRC sh
   gcc <OBJECTFILENAME> -o <PROGRAMFILENAME>
   #+END_SRC

   On Windows the =link= program from Microsoft Viusal Studio is used:

   #+BEGIN_SRC sh
   link /subsystem:console <OBJECTFILENAME> /out:<PROGRAMFILENAME>
   #+END_SRC

** Command-line Options

   The compiler accepts the following options in any order.

   - =-case-insensitive= :: Compile source code in case-insensitive mode.
	The default is to be case-sensitive.

   - =-comment= :: Emit source-code forms as comments in generated
                 assembler code.

   - =-dump= :: Dump code after /canonicalization/, which is a normalizing
	      step between CPS-transformation and closure-conversion.

   - =-dump-cc= :: Dump code after closure conversion and stop.

   - =-dump-cps= :: Dump source code to stdout after CPS-transformation 
		  and stop.

   - =-dump-features= :: Dump the set of enabled features after any
                       program specification has been completely
                       parsed.

   - =-dump-nested= :: Instead of dumping the source code as separate
		     =lambda= expressions, dump it in its real nested
		     structure. Only useful in combination with =-dump=,
		     =-dump-cps= or =-dump-cc=.

   - =-dump-source= :: Dump source code after before syntax expansion.

   - =-expand= :: Dump source code to stdout after syntax-expansion and
                stop.

   - =-feature FEATURE= :: Define =FEATURE=, for use in
        program-specifications or =cond-expand= clauses.

   - =-L LIBRARYPATH= :: Tells the compiler where to look for files to
        include directly or indirectly from program
        specifications. This option may be given multiple times where
        every occurence of a library-path is prepended to the search
        path.

   - =-nostdlib= :: Do not wrap the source code into a default program
                  specification as described above. This is mainly
                  useful when you have pre-expanded code that was
                  earlier produced by using =-expand=.

   - =-o FILENAME= :: Write generated code to =FILENAME= instead of
                    stdout.

** Configuration Macros for Generated Assembler Code

  - =DISABLE_WRITE_BARRIER= :: When mutating data-structures that are
       not stored in the heap, the program normally aborts with an
       error message. Define this macro to disable this check.

  - =EMBEDDED= :: Embed the generated code in another program. The compiled
		Scheme code can be invoked by calling the =bones= function,
		unless =PREFIX= is defined.

  - =ENABLE_GC_LOGGING= :: Write some informational output to stderr
       every time a garbage collection is triggered.

  - =PREFIX= :: Defines a custom prefix, so passing =-DEMBEDDED
              -DPREFIX=my= to =nasm=, the Scheme toplevel can be run
              by calling =my_bones=.

  - =TOTAL_HEAP_SIZE= :: Total size of the heap. Half of this space can be
       in use at any time. Defaults to 100MB.

* Language Description

** Program Specifications

*** Syntax

    Program specifications follow mostly the format as defined in the
     [[http://srfi.schemers.org/srfi-7/srfi-7.html][SRFI-7 specification]], with the following extensions:

    - =(cond-expand ...)= :: Can be used interchangebly with =feature-cond=.

    - =(error STRING)= :: Report error and abort compilation.

    - =(include FILENAME ...)= :: Includes more program-specification
         clauses from =FILENAME=.

    - =(provide FEATURE ...)= :: Adds additional features to the set of
         currently active features visible by =cond-expand= and
         =feature-cond= clauses. =FEATURE= should be a symbol.

*** Builtin Features

    Features available by default are: =bones=, =srfi-0=, =srfi-7=,
    =srfi-46=.

    By including =base.scm=, which contains the library of R5RS
    standard definitions and some non-standard primitives, the
    following addition features are available: =flonums=, =ieee-754=,
    =linux=, =srfi-6=, =file-ports=, =jiffy-clock=, =file-system= and
    =process-environment=.

** Deviations from R5RS

*** Section 1.3.2

    Argument types to primitive procedures are not checked. The only
    detected errors are errors related to port- and file-system
    operations, mutating literal constants or when the heap is
    exhausted.

*** Section 2

    BONES is by default case-sensitive, both at compile-time and at
    run-time.

*** Section 3.4

    Literal constants are immutable and destructively modifying such a
    constant will result in an error message being printed and the
    program will terminate.

*** Section 6

    Built-in procedures may be redefined (using =define= or
    =define-syntax=), but modifying them using assignment may or may
    not have the expected effect.

*** Section 6.1

    =eqv?= performs /structural/ comparison, which means it compares
    the contents of its two arguments. That means it will will return
    =#t= if both arguments have the same type and identical contents,
    even if the arguments are not numbers or characters.

    =eq?= will not necessarily return the expected result when
    comparing primitive procedures. Many of these will be compiled
    in-line using /identifier macros/, a feature of the used
    syntax-expander, which means that for example the two occurrences of 
    =zero?= below will refer to two different occurrences of the
    code for that primitive:

    #+BEGIN_SRC scheme
    (eq? zero? zero?)  ==> #f
    #+END_SRC

*** Section 6.2.1

    Only exact integers with 63 bits of magnitude (/fixnums/) and
    IEEE-754 extended precision floating point numbers (/flonums/) are
    supported. Numerical overflow is not detected, so arithmetic
    operations on fixnums will silently wrap on overflow.

*** Section 6.2.4
    
    The =#= character is not allowed inside inexact numeric constants.

*** Section 6.2.5

    =complex?= is not available.

    =max= and =min= return the maximal or minimal argument unchanged,
    without coercing between types in the case of arguments of mixes
    types.

    =numerator=, =denominator= and =rationalize= are not available.

    =log= is currently not available.

    =make-rectangular=, =make-polar=, =real-part=, =imag-part=,
    =magnitude= and =angle= are not available.

    The behaviour of the transcendental built-in procedures when given
    one of the special IEEE-754 numbers like /nan/ and /infinity/ is
    undefined.

*** Section 6.2.6

    =string->number= does not allow radix or exactness prefixes inside
    the given string argument, nor is the =#= character in inexact
    numeric strings supported.

    =string->number= and =number->string= only support the bases 8, 10
    and 16. Any other base is ignored and the conversion will be done
    using base 10.

*** Section 6.3.5

    The third argument to =substring= is optional and defaults to the
    length of the argument string.

*** Section 6.4

    =map= and =foreach= will terminate once any argument list ends.

    =force=, when given a argument that is not a promise will return
    that argument unchanged.

*** Section 6.5

    =eval=, =scheme-report-environment=, =null-environment= and
    =interaction-environment= are not avaialable.

*** Section 6.6.1

    =close-input-port= and =close-output-port= will signal an error
    when the port has already been closed.

*** Section 6.6.2

    =char-ready?= is not available.

*** Section 6.6.4

    =load=, =transcript-on= and =transcript-off= are not available.

** Extensions to R5RS

*** Section 2.2

    Expression-comments of the form =#;= are supported as in R7RS.

*** Section 4.2.2

    BONES supports the R7RS binding form =letrec*=.

*** Section 4.3.1

    BONES uses Al Petrofsky's "alexpander", which provides several
    enhancements. Among these /transformer/ expressions in
    =let-syntax= and =letrec-syntax= forms are extended to allow
    arbitrary expressions.

    The core generalization in this system is that both the
    transformer-specification and the expression in operator
    position of another expression may be any type of expression or
    syntax.  The four forms of syntax allowed are: a transformer (as
    allowed in the transformer-spec position in r5rs), a keyword (as
    allowed in the operator position in r5rs), a macro use that
    expands into a syntax, and a macro block (let-syntax or
    letrec-syntax) whose body is a syntax.

    Some examples:

     #+BEGIN_SRC scheme
     ;; a macro with a local macro
     (let-syntax ((foo (let-syntax ((bar (syntax-rules () ((bar x) (- x)))))
			   (syntax-rules () ((foo) (bar 2))))))
	 (foo))
     => -2

     ;; an anonymous let transformer, used directly in a macro call.
     ((syntax-rules ()
	  ((_ ((var init) ...) . body)
	   ((lambda (var ...) . body) init ...)))
	((x 1) (y 2))
	(+ x y))
     => 3

     ;; a keyword used to initialize a keyword
     (let-syntax ((q quote)) (q x)) => x

     ;; Binding a keyword to an expression (which could also be thought
     ;; of as creating a macro that is called without arguments).
     (let ((n 0))
	 (let-syntax ((x (set! n (+ n 1))))
	   (begin x x x n)))
     => 3

     (let-syntax ((x append)) ((x x))) => ()
     #+END_SRC

    Top-level macro blocks.

    At top level, if a macro block (a let-syntax or letrec-syntax form)
    has only one body element, that element need not be an expression
    (as would be required in r5rs).  Instead, it may be anything
    allowed at top level: an expression, a definition, a begin sequence
    of top-level forms, or another macro block containing a top-level
    form.

    #+BEGIN_SRC scheme
    (let-syntax ((- quote))
	(define x (- 1)))
    (list x (- 1)) => (1 -1)
    #+END_SRC

    Note that, unlike the similar extension in Chez scheme 6.0, this is
    still r5rs-compatible, because we only treat definitions within the
    last body element as top-level definitions (and r5rs does not allow
    internal definitions within a body's last element, even if it is a
    begin form):

    #+BEGIN_SRC scheme
    (begin
	(define x 1)
	(let-syntax ()
	  (define x 2)
	  'blah)
	x)
    => 1, in r5rs and alexpander, but 2 in Chez scheme

    (begin
	(define x 1)
	(let-syntax ()
	  (begin (define x 2)
		 'blah))
	x)
    => 2, in alexpander and in Chez scheme, but an error in r5rs.
    #+END_SRC

*** Section 4.3.2

    "Alexpander" fully supports [[http://srfi.schemrs.org/srfi-46][SRFI-46]], including tail-patterns and
    user-selectable ellipses.

*** Section 5.2.2

    Internal definitions expand into =letrec*= forms, as in R7RS.

    Expressions among internal definitions.

    A definition of the form (define <expression>) causes the
    expression to be evaluated at the conclusion of any enclosing set
    of internal definitons.  That is, at top level, (define
    <expression>) is equivalent to just plain <expression>.  As for
    internal definitions, the following are equivalent:

    #+BEGIN_SRC scheme
    (let ()
	(define v1 <init1>)
	(define <expr1>)
	(define <expr2>)
	(define v2 <init2>)
	(define <expr3>)
	(begin
	  <expr4>
	  <expr5>))

    (let ()
	(define v1 <init1>)
	(define v2 <init2>)
	(begin
	  <expr1>
	  <expr2>
	  <expr3>
	  <expr4>
	  <expr5>))
    #+END_SRC

*** Section 5.3

    The /transformer spec/ of a =define-syntax= form may be any
    expression.

*** Section 6.6.1

    =current-input-port= and =current-output-port= accept a single
      argument, a /port/, which changes the current default input- and
      output port.

*** Syntax Extensions

    The following non-standard syntax is available:

    - =(assert EXP [MSG ARGUMENT ...])= :: signals an error if =EXP=
         evaluates to =#f=, passing =MSG= and =ARGUMENTS ...= to
         =error= in that case.

    - =(begin0 EXP1 EXP ...)= :: evaluates the expressions and returns the
	 result value(s) of the first expression.

    - =(cond-expand CLAUSE ...)= :: The [[http://srfi.schemers.org/srfi-0/][SRFI-0]] expansion-time conditional.

    - =(cut EXP ...)= :: Notation for specializing parameters without
	 currying - see [[http://srfi.schemers.org/srfi-26/][SRFI-26]] for more information.

    - =(define-syntax-rule (NAME ARGUMENTS ...) BODY)= :: A more concise
        way of defining single-rule syntax.

    - =(define-values (VAR ...) EXP)= :: Evaluates =EXP= and binds =VAR= ...
	 to the values returned by it.

    - =(fluid-let ((VAR EXP) ...) BODY ...)= :: Syntax for dynamic scoping,
	 see [[http://srfi.schemers.org/srfi-15/][SRFI-15]] for more information.

    - =(let-optionals VAR1 ((VAR EXP) ... [RVAR]) BODY ...)= :: Destructures
	 the list in =VAR1=, binding the optional arguments =VAR= ... with
	 defaults taken from =EXP= ... Any remaining list elements can be
	 bound in the optional final variable =RVAR=.

    - =(letrec* ((VAR VAL) ...) BODY ...)= :: Binds =VAR= ... to the results of
	 evaluating =VAL= ... and evaluates =BODY=, with the variables being
	 in scope during the evaluation of their values. Mostly equivalent
	 to =letrec= but binds the variables sequentially.

    - =(when EXP BODY ...)= :: Equivalent to =(if EXP (begin BODY ...))=.

    - =(unless EXP BODY ...)= :: Equivalent to =(if (not EXP) (begin BODY ...))=.

*** Additional procedures

**** Fixnum Arithmetic

    - =(arithmetic-shift N M)= :: Shifts =N= =M= bits to the left, if
      =M= is positive, or to the right, if negative.

    - =(bitwise-and N M)= :: Binary AND.

    - =(bitwise-ior N M)= :: Binary inclusive OR.

    - =(bitwise-xor N M)= :: Binary exclusive OR.

    - =(bitwise-not N)= :: Binary invertion.

**** Input/Output

    - =(case-sensitive [BOOL])= :: If set to true, =read= will preserver case
      when reading symbols (this is the default).
 
    - =(current-error-port [PORT])= :: Returns or sets the port where
      error-messages are written to.

    - =(eof-object)= :: Returns the /end-of-file/ object.

    - =(get-output-string PORT)= :: Returns the currently accumulated output
      from the string-port =PORT=. 

    - =(open-append-output-file STRING)= :: Opens the file =STRING= in
     /append/ mode, and returns an output port.

    - =(open-input-string STRING)= :: Returns an input-port oin =STRING=
      from which data can be read.

    - =(open-output-string)= :: Returns an output-port accumulating all
      output written to into a string.

    - =(port? OBJECT)= :: Returns =#t= if =OBJECT= is an input- or output-port
      or =#f= otherwise.

    - =(print OBJECT ...)= :: Writes the arguments to the current output port
      (using =display=) followed by a newline.

    - =(read-string COUNT [PORT])= :: Reads =COUNT= characters from =PORT= and
      returns a string. If no input is available from =PORT=, the /end-of-file/
      object is returned. =PORT= defaults to the value of =(current-input-port)=.

    - =(write-string STRING [PORT])= :: Writes the characters in =STRING= to =PORT=,
      which defaults to the current output port.

**** Process Environment

    - =(command-line)= :: Returns the name of the running program and
      all arguments given on the command-line as a list of
      strings. When the program is running in /embedded/ mode, then
      this procedure returns the empty list.

    - =(current-process-id)= :: Returns the /ID/ of the current process
      as an exact integer.

    - =(get-environment-variable STRING)= :: Returns the value of the
      /environment variable/ named by =STRING= as a string, or =#f= if
      such an environment variable is not defined.

    - =(system STRING)= :: Passes =STRING= as a shell-command to be
      executed and returns the exit-status of the invoked command as
      an exact integer.

**** File System

    - =(current-directory [STRING])= :: When called without arguments,
      this procedure returns the name of the current working
      directory.  When given an argument, the current working
      directory is changed to =STRING=.

    - =(delete-file STRING)= :: Deletes the file designated by =STRING=.

    - =(file-exists? STRING)= :: Returns =STRING= if the file designated by
      =STRING= exists or =#f= otherwise.

**** Time

    - =(current-jiffy)= :: Returns the time since process startup, in
      some internal unit. Use =jiffies-per-second= to obtain the number
      of internal time units per second.

    - =(current-second)= :: Returns the current time, in seconds since
      the start of the /epoch/.

    - =(jiffies-per-second)= :: Returns the number of internal time
     units per second as an exact integer.

**** Control Flow

    - =(call/cc PROC)= :: Identical to =call-with-current-continuation=.

    - =(emergency-exit [CODE])= :: Terminates the current program
      immediately.  Still pending =dynamic-wind= thunks are not
      invoked. =CODE= is the exit code of the process and defaults to
      0.

    - =(exit [CODE])= :: Terminates the process with the process
     status =CODE= (or 0, if not given). Pending =dynamic-wind= after
     thunks will be executed.

    - =(return-to-host RESULT)= :: suspends the currently running
      program and returns =RESULT= to the caller. This procedure is
      only available when the =embedded= feature is defined.

**** Error-handling and Exceptions

    - =(current-exception-handler [PROCEDURE])= :: Sets the current
         /exception handler/, a procedure to be called when an error
         is signalled. The procedure will be called with an object
         that was used as an argument to =raise= or with an
         /error-object/. The default exception handler writes the
         exception object to the port that is the current value of
         =current-error-port= and performs an immediate exit (as with
         =emergency-exit=). In embedded mode, the default exception
         handler invokes =return-to-host= with the exception object as
         argument.  =current-exception-handler= is a parameter.

    - =(error [LOCATION] [MESSAGE] ARGUMENTS ...)= :: Creates an
      error-object from =LOCATION=, =MESSAGE= and =ARGUMENTS= and
      invokes the current exception handler. =LOCATION= can be used to
      mark where the error occurred and should be a symbol.

    - =(error-object? X)= :: Returns true if =X= is an error-object or
	 false otherwise.

    - =(error-object-irritants ERROROBJECT)= :: Returns the
         error-arguments stored in =ERROROBJECT=.

    - =(error-object-location ERROROBJECT)= :: Returns the
	 location stored in an error object or =#f= if no location
	 is available.

    - =(error-object-message ERROROBJECT)= :: Returns the
         error-message stored in =ERROROBJECT=.

    - =(file-error? OBJECT)= :: Returns true if =OBJECT= is an error
         object raised by an invalid file-operation or false
         otherwise.

    - =(raise OBJECT)= :: Raises an exception by calling the current
	 exception handler with =OBJECT=.

    - =(read-error? OBJECT)= :: Returns true if =OBJECT= is an error
         object raised invalid syntax in an invocation of =read= or
         false otherwise.

**** Numeric Operations

    - =(finite? NUMBER)= :: Returns =#t= if =NUMBER= is not positive or
     negative /infinity/.

    - =(nan? NUMBER)= :: Returns =#t= if =NUMBER= is the IEEE754 /nan/
     object or =#f= otherwise.

**** Parameters

    - =(make-parameter VALUE [GUARD])= :: Returns a /parameter/
      procedure that accepts a single optional argument. If that
      procedure is called without arguments, it returns =VALUE=. If it
      is called with an argument, the current value of the parameter
      is changed to this argument and subsequent 0-argument
      invocations if the procedure will return the new value. If
      =GUARD= is given, then it should be a procedure of one argument
      that checks or converts any values given to the parameter
      procedure.

    - =(parameterize ((PARAM VALUE) ...) BODY ...)= :: Dynamically binds
      parameters to the given values and executes =BODY= ... Note that
      the =PARAM= arguments are evaluated. After =BODY= ... is
      executed, the parameters are restored to their old values, with
      any guard-procedures temporarily disabled.

**** Miscellaneous

    - =(free)= :: Returns the currently available memory in heap as an
      exact integer.

    - =(reclaim)= :: Reclaims unused memory in the heap and returns an
      undefined value. Garbage collection is done automatically, but
      in certain cases, for example if time-critical code is to be
      executed, it may be useful to delay the next garbage collection
      as much as possible.

    - =(void ARGUMENT ...)= :: Ignores its arguments and returns an
      undefined result.

* Compiler Details

** Compilation Strategy

   The compiler is based on /Continuation Passing Style/ and does a
   straightforward translation of the CPS-transformed source code into
   x86_64 assembly language. The compiler is deliberately simple in
   its design to be easy to understand and modify, so very few
   optimizations are done.

   Procedures never return: an implicitly passed /continuation/
   argument holds a closure the is to be called with the result(s) of
   the current procedure and every call is a tail-call, and can be
   done via a direct jump.

   The /closure conversion/ adds another implicit argument, the
   current closure. This object contains a pointer to the actual code
   of a procedure plus the values of any /free variables/, or, in the
   case of free variables that are assigned, /cells/ holding the
   value. These cells can be shared between different closures that
   refer to the same free variable which ensures that assignments by
   one closure are seen in the other.

   Finally code is generated, currently in =NASM= assembler syntax.
   The code includes one or more support libraries that provide core
   runtime routines and the garbage collector.

** Compiler Stages

   The compiler performs the following passes over the source code:

   1. The source program is read into memory and the =program= form
      of the configuration language are expanded, if it exists.
   
   2. Macros are expanded resulting in the code to be free of any
      derived syntactic forms.

   3. The code is /canonicalized/, which means that some superficial
      simplifications are performed. Additional certain special forms
      are ocnverted into simpler internal forms. Variables are
      consistently renamed (called /alpha conversion/), to that every
      variable is uniquely named.

   4. The program is CPS-transformed.

   5. Next, unused local variables are identified and accordingly
      marked. A later pass will remove these variables if they are
      bound to expressions that are free of side-effects.

   6. The program is /closure converted/, that is, closure-allocations
      are made explicit.

   7. Assembler code is generated from the results of the previous
      passes.

** Register Usage

   The machine registers are used in the following manner:

   | Register name                        | Usage                                |
   |--------------------------------------+--------------------------------------|
   | rax, r11, r15                        | Temporary registers                  |
   | rcx, rdx, rsi, rdi, r8, r9, r10, r12 | Argument registers                   |
   | rbx                                  | Holds currently executing closure    |
   | rbp                                  | Allocation-pointer                   |
   | r13                                  | Allocation-limit                     |
   | r14                                  | Contains the internal value for "#f" |

   Since CPS-transformed procedures never return, registers need not
   be saved when a procedure call is made. In every procedure-call the
   registers =rbx=, =rcx=, ..., =r12= hold the actual arguments,
   including the implicit arguments introduced by the CPS- and
   closure-conversion passes: the current continuation (=rcx=) and the
   current closure (=rbx=), respectively. Local variables (as created
   by =let= or =letrec=) are also put into the remaining argument
   registers as long as registers are still available.

   =eax=, =r11= and =r15= are used throughout compiled code and the
   runtime-system as temporaries.

   =rbp= holds the /allocation pointer/, a pointer to the next
   available space in the /heap/. =r13= holds the heap-limit and once
   the allocation pointer is equal or higher than the limit, a garbage
   collection will be triggered.

   =r14= holds the value of the =#f= (false) constant, to speed up
   boolean tests.

** Optimizations Performed

   As already stated, not many optimizations are performed. Currently
   these are:

   During the canonicalization phase =lambda= or =case-lambda=
   expressions in the operator-position of a procedure-call are expanded
   in-line so that

   #+BEGIN_SRC scheme
   ((lambda (VAR ...) BODY ...) ARGUMENTS ...)
   #+END_SRC

   is transformed into

   #+BEGIN_SRC scheme
   (let ((VAR ARGUMENT) ...) BODY ...)
   #+END_SRC

   Unused =let=-bound variables are removed, if they are initialized
   to expressions that have no side-effects. Unused variables will not
   use up an argument register, regardless of whether the
   initialization expression has effects or not.

   Some effort is made to reduce redundant saves of intermediate
   values when translating the arguments for a procedure-call, as
   target registers for call-arguments may conflict with the use of
   local variables during the set-up of the call. This is currently
   not overly sophisticated.

   Finally some very simple peephole-optimizations are done, like a
   move from between identical registers.

** TODO Performance

** TODO Hacking and Extending the Compiler

* Data Representation

  Values used in the system are of two kinds: 64-bit immediate exact
  numbers (/fixnums/) and 64-bit pointers to data. A fixnum is marked
  by having the lowest bit set to 1. Pointers are always aligned on an
  8-byte boundary and so automatically have their lowest 3 bits set
  to 0. This allows to distinguish between immediate and non-immediate
  data by just testing the lowest bit. This is necessary to implement
  type-predicates and to allows the garbage collector (described
  below) to handle them specifically.

  Fixnums represent an integer value shifted one bit to the left, 
  with the lowest bit set.

  Non-immediate data (/blocks/) are preceded by a 64-bit /header/,
  containing the size and the type of the block, in addition to some
  bits used for house-keeping during garbage collections. The size is
  encoded in the lowest 56 bits, the type in the upper 8 bits.

  Non-immediate data is again classified into normal blocks,
  containing other values (fixnums or pointers to blocks) and
  /byteblocks/, where the actual data-area after the header contains
  raw bytes. Among these are strings and floating-point numbers.

  The last class of blocks are /special/ blocks, which are like normal
  blocks, but with the first /slot/ holds a native pointer value. This
  is used for procedures - the pointer in that case points to the
  actual machine code of the procedure. The remaining slots hold free
  variables, in case the procedure is a closure, i.e.  needs to retain
  references to variables defined in a scope lexically outside of the
  procedure.

  BONES uses IEEE-754 floating-point numbers on all supported
  platforms.

  Here is a rough overview of the different objects used in the
  system:

  | Type        | Typecode | Immediate | Byteblock | Special | Slots                              | Remarks             |
  |-------------+----------+-----------+-----------+---------+------------------------------------+---------------------|
  | Fixnum      | -        | X         |           | -       |                                    |                     |
  | Null        | #x00     |           |           |         | None                               | The empty list      |
  | Symbol      | #x01     |           |           |         | String                             |                     |
  | Pair        | #x02     |           |           |         | Car, Cdr                           |                     |
  | Vector      | #x03     |           |           |         | Element1, ...                      |                     |
  | Char        | #x04     |           |           |         | Code (fixnum)                      |                     |
  | End-of-file | #x05     |           |           |         | None                               |                     |
  | Void        | #x06     |           |           |         | None                               | The undefined value |
  | Boolean     | #x07     |           |           |         | 1 or 0 (fixnum)                    |                     |
  | Port        | #x08     |           |           |         | fd (fixnum), input-flag (boolean), |                     |
  |             |          |           |           |         | close-proc, r/w-proc, peek-buf     |                     |
  |             |          |           |           |         | (char or #f), port-data            |                     |
  | Promise     | #x09     |           |           |         | Thunk (procedure)                  |                     |
  | Record      | #x0a     |           |           |         | Tag (symbol), id (fixnum), field1, |                     |
  |             |          |           |           |         | ...                                |                     |
  | Flonum      | #x10     |           | X         |         |                                    |                     |
  | String      | #x11     |           | X         |         |                                    |                     |
  | Procedure   | #x20     |           |           | X       |                                    |                     | 

  =#t=, =#f= and the undefined (void) value are unique and never
  allocated.

  For information about the use of the slots in port and record
  objects, you should study the source code, in particular =r5rs.scm=.

* Garbage Collection

  BONES uses a Cheney-style copying garbage collector. This sacrifices
  one half of the available heap space to gain faster allocation and
  collection and to make the time needed to collect garbage
  independent on the amount of available memory. Fixnums are ignored
  during GC, blocks are traversed in breadth-first manner to copy all
  live data in every collection into the second half of the
  heap-space.  Once all live data has been copied, the halves of the
  heap-space are /flipped/ and program execution continues. The time
  needed to a GC depends on the amount of live data. The fewer data is
  allocated, the lower is the impact of the GC on the total run-time
  of a program.

  Pointers that do not point into the garbage collected heap are
  ignored by GC, so it is allowed to store pointers to user-allocated
  blocks (in fact to any kind of data) into Scheme data-structures.

  Note that storing pointers to heap-allocated data in non-heap data
  is disallowed and checked at runtime. Otherwise the garbage
  collector will not be able to detect that the stored value is still
  live, if no other pointer to that object exists. Since the GC moves
  data in the heap on every collection (because it is copied from the
  old heap-space to the new one), the old pointer will be invalid
  after the collection finishes. This check can be disabled by passing
  =-DDISABLE_WRITE_BARRIER= to =nasm=, which gives better performance,
  but may lead to very hard to find bugs.

* Interfacing to Foreign Code

  There are basically four ways to invoke non-Scheme code from compiled
  programs:

  1. Use =system= to run shell commands. This is the easiest and most
     portable method, unless you need to have access the BONES
     runtime- system or want to modify or inspect Scheme data.

  2. Embed a compiled program inside other code that can interface to
     C. For more information on this see below. This is also quite
     straightforward and very flexible, without the need to use
     assembler.

  3. Use the =$inline= special form to mix assembler instructions
     directly with Scheme code, where =$inline= is defined as

     - =($inline STRING ARGUMENT ...)= :: Executes the assembler
          instructions in =STRING=, given the results of evaluating
          the arguments in =ARGUMENTS=, specifically in the =rax=,
          =r11= and =r15= registers. At most three arguments may be
          passed. Multiple instructions inside =STRING= can be given,
          when separated by =;= (semicolon). Note that changing other
          registers than the ones used for passing arguments may
          change local variables and thus should be avoided, unless
          you really know what you are doing.

  4. Use the =$primitive= special form to refer to a primitive
     procedure written in assembler:

     - =($primitive STRING)= :: Returns a procedure refering to the
	  primitive procedure named by the label =STRING=. 

     The procedure must be written in assembler and takes its
     arguments in the argument registers described in the chapter
     describing the register usage. =rbx= holds the current procedure,
     =rcx= the current continuation (a procedure block), and =rdx= to
     =r12= contain the first seven arguments passed to the current
     procedure. Additional arguments are passed in a static array and
     are not accessible from separately compiled code, so your
     primitive may not accept more than seven arguments.

     To return, invoke the continuation procedure with a single result
     in =rcx=, like this (nasm syntax, assuming the result is in =rax=):

     #+BEGIN_SRC asm
     mov rbx, rcx            ; make continuation the current procedure
     mov rcx, rax            ; put result into the correct register
     mov rax, [rbx + 8]      ; get code-pointer to continuation
     jmp rax                 ; and jump to it
     #+END_SRC

     During execution of your primitive you are free to modify all
     registers as you please, with the exception of =rbp=, =r13= and
     =r14=, as long as you follow the steps given to invoke the
     continuation. =rsp= may be modified, but must be restored when
     the primitive returns.

     No implicit argument-count checks are done. Returning multiple
     values from user-defined primitives is not supported. The stack
     is not used for procedure call arguments or return-addresses.

* TODO Embedding

* Bugs and Limitations

  =log= is currently not implemented, as I haven't found out yet how to
  define it using SSE2/x87 operations.

  The heap has a fixed size and does not resize dynamically. You can
  change the default size of the heap setting the =TOTAL_HEAP_SIZE=
  configuration macro when assembling a compiled program.

  =inexact->exact= uses the =FISTTP= instruction, so a CPU with SSE3
  support is required.

  Complex numbers and other numeric types with the exception of small
  integers and floating-point numbers are not supported.

  =string->number= does not detect overflow when converting integers
  and return -1 if the result does not fit into a fixnum. Also, "+/-nan.0"
  and "+/-inf.0" is not correctly detected (but "+/-nan

  Library support for on Linux for "nolibc" mode is incomplete:

  - =number->string= and =string->number= do not support inexact numbers
  - The non-standard primitives =system= and =getenv= are currently not
    implemented.
  
* TODO Porting Guide

* TODO Suggestions for Projects

* Terms of Use

  Some parts of BONES are not by the author, but have been taken from
  other sources:

    The pretty-printer (pp.scm) is

    Copyright (c) 1991, Marc Feeley
    Author: Marc Feeley (feeley@iro.umontreal.ca)
    Distribution restrictions: none

    The syntax-expander (alexpand.scm) is

    Copyright 2002-2004 Al Petrofsky <alexpander@petrofsky.org>

    Redistribution and use in source and binary forms, with or without
    modification, are permitted provided that the following conditions
    are met:

     Redistributions of source code must retain the above copyright
       notice, this list of conditions and the following disclaimer.

     Redistributions in binary form must reproduce the above copyright
       notice, this list of conditions and the following disclaimer in
       the documentation and/or other materials provided with the
       distribution.

     Neither the name of the author nor the names of its contributors
       may be used to endorse or promote products derived from this
       software without specific prior written permission.

    THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
    "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
    LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
    A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
    HOLDERS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
    INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
    BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
    OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
    AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
    LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY
    WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
    POSSIBILITY OF SUCH DAMAGE.

  Everything else was written by Felix Winkelmann and is put into the
  public domain.

* TODO Further Reading


#+TITLE:     The BONES Manual
#+DESCRIPTION: 
#+KEYWORDS: 
#+LANGUAGE:  en
#+OPTIONS:   H:3 num:t toc:t \n:nil @:t ::t |:t ^:{} -:t f:t *:t <:t
#+OPTIONS:   TeX:nil LaTeX:nil skip:nil d:nil todo:t pri:nil tags:not-in-toc
#+INFOJS_OPT: view:nil toc:nil ltoc:t mouse:underline buttons:0 path:http://orgmode.org/org-info.js
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport
#+LINK_UP:   http://www.call-with-current-continuation.org/bones/
#+LINK_HOME: http://www.call-with-current-continuation.org
#+STYLE: <link rel="stylesheet" type="text/css" href="stylesheet.css" />
