;;;; MIPS specific compiler code, generates GAS syntax


(define fixnum-range '(-1073741824 . 1073741823))
(define temporary-registers '($v0 $v1 $a0 $a1))
(define argument-registers '($s5 $a2 $a3 $t0 $t1 $t2 $t3 $t4 $t5 $t6 $t7 $t8 $t9 $s0 $s1 $s2 $s3))
(define word-size 4)			; bytes
(define target-os 'linux)
(define target-arch 'mips)
(define target-endianness 'little-endian)
(define arg-register '$v0)
(define alloc-register '$s8)
(define self-register '$s5)
(define false-register '$s6)
(define count-register '$v1)
(define stack-register '$sp)
(define base-register '$s4)


(define (generate-header)
  (emit "/* GENERATED BY BONES */\n")
  (emit ".include \"mips/linux/boneslib.s\"\n"))

(define (generate-trailer)
  (emit "/* END OF GENERATED CODE */\n"))

(define (generate-primitives)
  (emit " .data\n")
  (for-each
   (match-lambda
     ((l . name)
      (emit l ": .word CLOSURE | 1\n .word " name "\n")))
   primitives))

(define (generate-section name)
  (emit name "\n"))

(define (generate-defword . vals)
  (emit " .word ")
  (for-each emit vals)
  (emit "\n"))

(define (generate-defbyte . vals)
  (emit " .byte ")
  (for-each emit vals)
  (emit "\n"))

(define (generate-deffloat val)
  (emit " .double " val "\n"))

(define (generate-align bytes)
  (emit " .balign " bytes "\n"))

(define (generate-padding bytes)
  (emit " .fill " bytes "\n"))

(define (generate-equ name . vals)
  (emit ".equ " name ", ")
  (for-each emit vals)
  (emit "\n"))

(define (generate-closure-alloc t n id)
  (emit " li " t ", CLOSURE | " (add1 n) "\n sw " t ", 0($s8)\n"
	" li $v1, f_" id "\n sw $v1, " (cells 1) "($s8)\n"))

(define (generate-move dest src)
  (emit " move " dest ", " src "\n"))

(define (generate-add r n)
  (emit " addiu " r ", " r ", " n "\n"))

(define (generate-move-to-local off src)
  (emit " sw " src ", (locals - base + " off ")($s4)\N"))

(define (generate-reserve-on-stack bytes)
  (emit " addiu $sp, $sp, " (- bytes) "\n"))

(define (generate-pop-stack bytes)
  (emit " addiu $sp, $sp, " bytes "\n"))

(define (generate-comment . text)
  (emit "/* ")
  (for-each emit text)
  (emit " */\n"))

(define (generate-global-store var name src)
  (emit " sw " src ", (" name " - base)($s4) # (set! " var " ...)\n"))

(define (generate-global-ref dest var name)
  (emit " lw " dest ", (" name " - base)($s4) # " var "\n"))

(define (generate-local-ref dest var src)
  (emit " lw " dest ", (locals - base + " src ")($s4) # " var "\n"))

(define (generate-local-store var dest src)
  (emit " sw " src ", (locals - base + " dest ")($s4) # (set! " var " ...)\n"))

(define (generate-conditional-branch r lbl)
  (emit " bne " r ", $s6, " lbl "\n"))

(define (generate-jump lbl)
  (emit " j " lbl "\n"))

(define (generate-immediate-ref dest val . comment)
  (emit " li " dest ", " val " # ")
  (for-each emit comment)
  (emit "\n"))

(define (generate-slot-ref dest src off)
  (emit " lw " dest ", " off "(" src ")\n"))

(define (generate-slot-store dest off src)
  (emit " sw " src ", " off "(" dest ")\n"))

(define (generate-true-ref r)
  (emit " addiu " r ", $s6, 4\n"))

(define (generate-alloc-check-and-call)
  (emit " bgt $s8, $s7, reclaim\n jr $v0\n"))

(define (generate-tail-call r)
  (emit " jr " r "\n"))

(define (generate-call name)
  (emit " jal " name "\n"))
