;;; Windows
(define-syntax %SIGINT 2)
(define-syntax %SIG_IGN 1)
(define-syntax %SIG_DFL 0)
(define-syntax %O_RDONLY 0)
(define-syntax %O_WRONLY 1)
(define-syntax %O_CREAT 256)
(define-syntax %O_TRUNC 512)
(define-syntax %O_APPEND 8)
(define-syntax %O_BINARY 32768)
(define-syntax %_S_IREAD 256)
(define-syntax %_S_IWRITE 128)
